# Created using wingetcreate

PackageIdentifier: Asana,Inc.AsanaforWindows
PackageVersion: 1.1.0
Installers:
- Architecture: x86
  InstallerType: exe
  InstallerUrl: https://desktop-downloads.asana.com/win32_x64/prod/latest/AsanaSetup.exe
  InstallerSha256: 237ECC4478214D109F52D61CADCE6A4E571BBF93D297FB6662F73052254ACC24
ManifestType: installer
ManifestVersion: 1.0.0
