# Created using wingetcreate

PackageIdentifier: clickbitsGmbH.clockodo
PackageVersion: 20210305083241
Installers:
- Architecture: x86
  InstallerType: nullsoft
  InstallerUrl: https://www.clockodo.com/apps/download/win/latest/clockodo-setup-6.0.10.exe
  InstallerSha256: A3D089AB203828E4046988ADF4B4DA2FC30906EBD76DEA023719BF775D5C8342
ManifestType: installer
ManifestVersion: 1.0.0
